# Generated by Django 4.2.25 on 2025-10-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petphoto',
            old_name='photo',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='age',
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
