# Generated by Django 4.2.25 on 2025-10-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_photo_petphoto_image_remove_pet_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
