# Generated by Django 4.2.25 on 2025-10-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_owner_birth_date_owner_city_owner_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='owner_pictures/'),
        ),
    ]
